device: "cuda"

data:
  paths:
    train: 
      - "./data/sim_people-1000_days-60_init-0.01_seed-7_20200423-130419-output"
      - "./data/sim_people-1000_days-60_init-0.01_seed-9_20200423-131911-output"
      - "./data/sim_people-1000_days-60_init-0.01_seed-5_20200423-124910-output"
    validate: 
      - "./data/sim_people-1000_days-60_init-0.01_seed-8_20200423-131153-output"
      - "./data/sim_people-1000_days-60_init-0.01_seed-6_20200423-125649-output"
  loader_kwargs:
    batch_size: 32
    shuffle: true
    num_workers: 4
    relative_days: true

model:
  kwargs:
    capacity: 128
    dropout: 0.1
    num_health_history_features: 13
    health_history_embedding_dim: 32
    num_health_profile_features: 14
    health_profile_embedding_dim: 32
    encounter_duration_embedding_mode: "thermo"
    encounter_duration_thermo_range: [0.0, 6.0]
    encounter_duration_num_thermo_bins: 32
    time_embedding_dim: 32
    encounter_duration_embedding_dim: 32
    num_encounter_partner_id_bits: 16
    encounter_partner_id_embedding_dim: 32
    message_dim: 8
    message_embedding_dim: 32
    num_heads: 4
    sab_capacity: 128
    num_sabs: 2
    pool_latent_entities: false
    use_logit_sink: false
    encounter_output_features: 1
    latent_variable_output_features: 1

losses:
  kwargs:
    infectiousness: {}
    contagion:
      allow_multiple_exposures: true
  weights:
    infectiousness: 1.
    contagion: 1.

optim:
  kwargs:
    lr: 0.0001

scheduler:
  use: false
  kwargs:
    eta_min: 0.00001
  warmup: false
  warmup_kwargs:
    multiplier: 1
    total_epoch: 4

training:
  num_epochs: 20

wandb:
  use: true
  log_every: 100
